name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build Docker image with latest and commit hash tags
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app-image:latest .

      - name: Push Docker image (latest)
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app-image:latest

      - name: Push Docker image (commit hash)
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app-image:${{ github.sha }}
