name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build Docker image with latest tag only
        run: |
          # Build the Docker image with latest tag only
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app-image:latest .

      - name: Push Docker images
        run: |
          # Get the short hash
          SHORT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
          # Tag the image with the short hash
          docker tag ${{ secrets.DOCKER_USERNAME }}/flask-app-image:latest \
                     ${{ secrets.DOCKER_USERNAME }}/flask-app-image:${SHORT_HASH}
          # Push the images
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app-image:${SHORT_HASH}
