name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build Docker image with latest and short commit hash tags
        run: |
          
          # Build the Docker image with both latest and short hash tags
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app-image:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/flask-app-image:${{ github.sha }} .

      - name: Push Docker images
        run: |
          SHORT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app-image:${SHORT_HASH}
